### ISSUE TITLE
Fails to build with yaxpeax-arch dep issue

### ISSUE THREAD

**Issue by iankronquist** [iximeow/yaxpeax-x86#1] opened 2020-01-13 19:19 UTC
```
C:\Users\iakronqu\source>git clone https://github.com/iximeow/yaxpeax-x86.git
Cloning into 'yaxpeax-x86'...
...
C:\Users\iakronqu\source\yaxpeax-x86>cargo build
    Updating crates.io index
error: failed to load source for a dependency on `yaxpeax-arch`

Caused by:
  Unable to update C:\Users\iakronqu\yaxpeax-arch

Caused by:
  failed to read `C:\Users\iakronqu\yaxpeax-arch\Cargo.toml`

Caused by:
  The system cannot find the path specified. (os error 3)
```

Steps to repro:
1. git clone  from github
2. cargo build
3. cargo can't find yaxpeax-arch in the relative path.

Not sure if this is by design or a documentation bug but I figured I'd open an issue.

**Comment by iximeow** [comment] 2020-01-13 20:53
it's a little of "by design" and a little of "documentation bug", sorry - until i have crates available, these dependencies happen to be laid out how i've been working on them. all `yaxpeax-*` decoders expect [https://github.com/iximeow/yaxpeax-arch](https://github.com/iximeow/yaxpeax-arch) to be present at `../../yaxpeax-arch` for the path dependency you're seeing at the moment.

you can either adjust `Cargo.toml` to have `yaxpeax-arch = { git = "https://github.com/iximeow/yaxpeax-arch.git" }`, or clone `yaxpeax-arch` as well. i have a few design questions to answer for `yaxpeax-arch` before putting it on crates.io, at which point i'll adjust dependencies to not involve where i happened to put repos :)

**Comment by iankronquist** [comment] 2020-01-13 22:29
I figured as much but wanted to report it in case this was just an oversight. Neat project!

**Comment by iximeow** [comment] 2020-01-18 09:30
oh right, yaxpeax-x86 and yaxpeax-arch are real crates that don't have weird path dependencies anymore. gonna close this since this should build off of crates.io without issue now.

**Closed by iximeow** 2020-01-18 09:30 UTC
